In [7]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

# sample XOR network
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 5)  # 2 input nodes, 5 in middle layers
        self.fc2 = nn.Linear(5, 1)  # 5 middle layer, 1 output node
        self.rl1 = nn.ReLU()
        self.rl2 = nn.ReLU()
    def forward(self, x):
        x = self.fc1(x)
        x = self.rl1(x)
        x = self.fc2(x)
        x = self.rl2(x)
        return x

net = Net()

In [8]:
#네트웍 파라미터들 표시해줌
net.state_dict()

OrderedDict([('fc1.weight', tensor([[ 0.3237, -0.2276],
                      [-0.4743,  0.1147],
                      [-0.5772,  0.7005],
                      [-0.4083,  0.6805],
                      [-0.4670, -0.0914]])),
             ('fc1.bias',
              tensor([-0.0046, -0.0348,  0.3284,  0.6702,  0.2633])),
             ('fc2.weight',
              tensor([[ 0.1509, -0.3814,  0.2621, -0.0716, -0.0952]])),
             ('fc2.bias', tensor([0.4308]))])

In [10]:
# 아래 방법으로 복사하는 방법도 있음
net2 = Net()
net2.load_state_dict(net.state_dict())

In [12]:
# 아래건 뭐지? state_dict()랑 다른건가? 이건 dict가 아니라 object가 나오네??
net.parameters()

<generator object Module.parameters at 0x11ac4cd58>

In [13]:
# object라기 보다 generator였네.. 아래처럼 하면 내용을 들여다 볼 수 있나보다..
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 0.3237, -0.2276],
        [-0.4743,  0.1147],
        [-0.5772,  0.7005],
        [-0.4083,  0.6805],
        [-0.4670, -0.0914]], requires_grad=True)
Parameter containing:
tensor([-0.0046, -0.0348,  0.3284,  0.6702,  0.2633], requires_grad=True)
Parameter containing:
tensor([[ 0.1509, -0.3814,  0.2621, -0.0716, -0.0952]], requires_grad=True)
Parameter containing:
tensor([0.4308], requires_grad=True)
