In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable

# sample XOR network
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 5)  # 2 input nodes, 5 in middle layers
        self.fc2 = nn.Linear(5, 1)  # 5 middle layer, 1 output node
        self.rl1 = nn.ReLU()
        self.rl2 = nn.ReLU()
    def forward(self, x):
        x = self.fc1(x)
        x = self.rl1(x)
        x = self.fc2(x)
        x = self.rl2(x)
        return x

net = Net()

In [2]:
#네트웍 파라미터들 표시해줌
net.state_dict()

OrderedDict([('fc1.weight', tensor([[-0.6911, -0.1359],
                      [-0.6907,  0.1217],
                      [-0.4225,  0.5771],
                      [ 0.6387,  0.3361],
                      [-0.3418, -0.0449]])),
             ('fc1.bias',
              tensor([ 0.3638, -0.5852,  0.3752,  0.2166,  0.0893])),
             ('fc2.weight',
              tensor([[-0.1772,  0.2562, -0.3120,  0.4012, -0.3505]])),
             ('fc2.bias', tensor([-0.1292]))])

In [3]:
# 아래 방법으로 복사하는 방법도 있음
net2 = Net()
net2.load_state_dict(net.state_dict())

In [4]:
# 아래건 뭐지? state_dict()랑 다른건가? 이건 dict가 아니라 object가 나오네??
net.parameters()

<generator object Module.parameters at 0x11529b468>

In [5]:
# object라기 보다 generator였네.. 아래처럼 하면 내용을 들여다 볼 수 있나보다..
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.6911, -0.1359],
        [-0.6907,  0.1217],
        [-0.4225,  0.5771],
        [ 0.6387,  0.3361],
        [-0.3418, -0.0449]], requires_grad=True)
Parameter containing:
tensor([ 0.3638, -0.5852,  0.3752,  0.2166,  0.0893], requires_grad=True)
Parameter containing:
tensor([[-0.1772,  0.2562, -0.3120,  0.4012, -0.3505]], requires_grad=True)
Parameter containing:
tensor([-0.1292], requires_grad=True)


In [7]:
# 요거 잘은 모르겠는데 multiprocess 환경에서 net을 서로 공유할때 불러줘야 하는 함수인것 같다.
# https://pytorch.org/docs/stable/tensors.html
# https://pytorch.org/docs/stable/notes/multiprocessing.html
# multiprocess 환경에서의 간단한 pytorch sample은 다음 링크 참조
# https://github.com/MorvanZhou/pytorch-A3C
net.share_memory()

Net(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=1, bias=True)
  (rl1): ReLU()
  (rl2): ReLU()
)